import { useAnalysis } from "@/context/AnalysisContext";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, ShieldAlert, FileWarning, ArrowRight, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";

function SeverityBadge({ level }: { level: string }) {
  let color = "bg-primary/20 text-primary border-primary/30";
  if (level === "CRITICAL") color = "bg-destructive/20 text-destructive border-destructive/30";
  if (level === "HIGH") color = "bg-orange-500/20 text-orange-500 border-orange-500/30";
  if (level === "MEDIUM") color = "bg-amber-500/20 text-amber-500 border-amber-500/30";
  if (level === "LOW") color = "bg-green-500/20 text-green-500 border-green-500/30";

  return <Badge variant="outline" className={`px-3 py-1 text-xs font-bold ${color}`}>{level} SEVERITY</Badge>;
}

export default function Analysis() {
  const { analysisResult } = useAnalysis();

  if (!analysisResult) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-8 text-center space-y-4">
        <ShieldAlert className="w-16 h-16 text-muted-foreground opacity-50" />
        <h2 className="text-xl font-semibold">No active analysis</h2>
        <p className="text-muted-foreground">Submit a report to see the analysis results.</p>
        <Link href="/report">
          <Button variant="outline">Go to Report Form</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="container max-w-5xl mx-auto py-8 px-4 space-y-8">
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Threat Analysis Report</h1>
          <p className="text-muted-foreground mt-1">Generated by CyberGuide AI</p>
        </div>
        <SeverityBadge level={analysisResult.severityLevel} />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="md:col-span-2 border-border/50 bg-card/40 backdrop-blur">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Classification</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xl font-medium text-foreground">{analysisResult.fraudClassification}</p>
            {analysisResult.aiGuidance && (
              <p className="mt-4 text-sm text-muted-foreground p-4 bg-muted/50 rounded-lg border border-border/50">
                {analysisResult.aiGuidance}
              </p>
            )}
          </CardContent>
        </Card>

        <Card className="border-border/50 bg-card/40 backdrop-blur">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Recovery Odds</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center py-4">
            <div className="text-5xl font-bold text-primary mb-2">
              {analysisResult.recoveryProbability}%
            </div>
            <p className="text-xs text-muted-foreground uppercase tracking-wider">Estimated Probability</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="border-destructive/20 bg-destructive/5 backdrop-blur">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2 text-destructive">
              <AlertTriangle className="w-5 h-5" />
              Risk Indicators
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              {analysisResult.riskIndicators.map((risk, i) => (
                <li key={i} className="flex items-start gap-2 text-sm">
                  <div className="mt-1 w-1.5 h-1.5 rounded-full bg-destructive shrink-0" />
                  <span className="text-foreground/90">{risk}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card className="border-primary/20 bg-primary/5 backdrop-blur">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2 text-primary">
              <ShieldAlert className="w-5 h-5" />
              Immediate Actions Required
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-4">
              {analysisResult.emergencyActions.slice(0, 3).map((action, i) => (
                <li key={i} className="flex flex-col gap-1">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="px-1.5 py-0 text-[10px]">Step {action.order}</Badge>
                    <span className="text-sm font-semibold">{action.title}</span>
                  </div>
                  <span className="text-xs text-muted-foreground pl-12">{action.description}</span>
                </li>
              ))}
            </ul>
            <div className="mt-6 pt-4 border-t border-border/50">
              <Link href="/emergency">
                <Button variant="ghost" className="w-full text-primary hover:text-primary hover:bg-primary/10">
                  View Full Emergency Protocol <ArrowRight className="w-4 h-4 ml-2" />
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}